// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Greeter$Type } from "./Greeter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Greeter"]: Greeter$Type;
    ["contracts/Greeter.sol:Greeter"]: Greeter$Type;
  }
}
