// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { AbiParameterToPrimitiveType, GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Greeter$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Greeter",
  "sourceName": "contracts/Greeter.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_number",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "getNumber",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "greet",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "greeting",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "number",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_number",
          "type": "uint256"
        }
      ],
      "name": "setNumber",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x608060405234801561001057600080fd5b506040516103af3803806103af8339818101604052810190610032919061007a565b80600081905550506100a7565b600080fd5b6000819050919050565b61005781610044565b811461006257600080fd5b50565b6000815190506100748161004e565b92915050565b6000602082840312156100905761008f61003f565b5b600061009e84828501610065565b91505092915050565b6102f9806100b66000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c80633fb5c1cb1461005c5780638381f58a14610078578063cfae321714610096578063ef690cc0146100b4578063f2c9ecd8146100d2575b600080fd5b610076600480360381019061007191906101ba565b6100f0565b005b6100806100fa565b60405161008d91906101f6565b60405180910390f35b61009e610100565b6040516100ab91906102a1565b60405180910390f35b6100bc61013d565b6040516100c991906102a1565b60405180910390f35b6100da610176565b6040516100e791906101f6565b60405180910390f35b8060008190555050565b60005481565b60606040518060400160405280601481526020017f48656c6c6f2066726f6d20636f6e747261637421000000000000000000000000815250905090565b6040518060400160405280601481526020017f48656c6c6f2066726f6d20636f6e74726163742100000000000000000000000081525081565b60008054905090565b600080fd5b6000819050919050565b61019781610184565b81146101a257600080fd5b50565b6000813590506101b48161018e565b92915050565b6000602082840312156101d0576101cf61017f565b5b60006101de848285016101a5565b91505092915050565b6101f081610184565b82525050565b600060208201905061020b60008301846101e7565b92915050565b600081519050919050565b600082825260208201905092915050565b60005b8381101561024b578082015181840152602081019050610230565b60008484015250505050565b6000601f19601f8301169050919050565b600061027382610211565b61027d818561021c565b935061028d81856020860161022d565b61029681610257565b840191505092915050565b600060208201905081810360008301526102bb8184610268565b90509291505056fea2646970667358221220c9752d6007f8eadd526a8069895fab7d3512d35eaf38539326efdce19b234e2964736f6c63430008180033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b50600436106100575760003560e01c80633fb5c1cb1461005c5780638381f58a14610078578063cfae321714610096578063ef690cc0146100b4578063f2c9ecd8146100d2575b600080fd5b610076600480360381019061007191906101ba565b6100f0565b005b6100806100fa565b60405161008d91906101f6565b60405180910390f35b61009e610100565b6040516100ab91906102a1565b60405180910390f35b6100bc61013d565b6040516100c991906102a1565b60405180910390f35b6100da610176565b6040516100e791906101f6565b60405180910390f35b8060008190555050565b60005481565b60606040518060400160405280601481526020017f48656c6c6f2066726f6d20636f6e747261637421000000000000000000000000815250905090565b6040518060400160405280601481526020017f48656c6c6f2066726f6d20636f6e74726163742100000000000000000000000081525081565b60008054905090565b600080fd5b6000819050919050565b61019781610184565b81146101a257600080fd5b50565b6000813590506101b48161018e565b92915050565b6000602082840312156101d0576101cf61017f565b5b60006101de848285016101a5565b91505092915050565b6101f081610184565b82525050565b600060208201905061020b60008301846101e7565b92915050565b600081519050919050565b600082825260208201905092915050565b60005b8381101561024b578082015181840152602081019050610230565b60008484015250505050565b6000601f19601f8301169050919050565b600061027382610211565b61027d818561021c565b935061028d81856020860161022d565b61029681610257565b840191505092915050565b600060208201905081810360008301526102bb8184610268565b90509291505056fea2646970667358221220c9752d6007f8eadd526a8069895fab7d3512d35eaf38539326efdce19b234e2964736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Greeter",
    constructorArgs: [_number: AbiParameterToPrimitiveType<{"name":"_number","type":"uint256"}>],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Greeter$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/Greeter.sol:Greeter",
    constructorArgs: [_number: AbiParameterToPrimitiveType<{"name":"_number","type":"uint256"}>],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Greeter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Greeter",
    constructorArgs: [_number: AbiParameterToPrimitiveType<{"name":"_number","type":"uint256"}>],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Greeter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/Greeter.sol:Greeter",
    constructorArgs: [_number: AbiParameterToPrimitiveType<{"name":"_number","type":"uint256"}>],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Greeter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Greeter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Greeter$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/Greeter.sol:Greeter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Greeter$Type["abi"]>>;
}
